// File automatically generated by `vite-plugin-module-list`
export default [
  { path: "curl.ts", module: () => import("./../../plugin/curl") },
  { path: "index.ts", module: () => import("./../../plugin/index") },
  { path: "md.ts", module: () => import("./../../plugin/md") },
];
